name: 'VU1 Dynamic Analogue Dial'
version: '0.1.0'
slug: 'vu1'
description: 'Control VU1 Dynamic Analogue Dials from Home Assistant'
url: 'https://github.com/leoherzog/home-assistant-vu1'
startup: application
boot: auto
uart: true
usb: true
ingress: true
ports:
  5340/tcp: 5340
options:
  log_level: 'info'
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  default_min_value: int
  default_max_value: int
